### PR TITLE
[New Feature] City Projects Pin

### PR DESCRIPTION
**Pull request by Charzard4261**
You can now pin a City Project by clicking on the description skull in the menu
It renders using Hypixel's given names and stuff, if you want items rendered too you'll need to either integrate NEU (check if it's installed) or make your own item list, since Hypixel only provides names
Does not save between Minecraft instances, and will not refresh if a contributions 24hr cooldown expires during the time it is pinned (unpin and repin to solve)
## Screenshots
CPP1
CPP2
CPP3

### CODE REVIEW

**Comment by unnown** [comment]
Might be me, but where is Le pin itself? ie. the pin.png

**Comment by IRONM00N** [comment]
This is cool

**Comment by unnown** [comment]
Very nice!
I'll deff adapt this code to also show Jacob's farming event

**Comment by Charzard4261** [comment]
Oh yeah, I need to mention that I have no idea how to properly set default values for the changed GUI system, so that needs to be fixed when merging.

**Comment by Phoube** [comment]
Good job wid dis!

**Comment by Charzard4261** [comment]
I seem to have fucked this branch over by accident, I thought the whole point of git was to let you separate branches and use version control not merge two with no warning.

**Pull request closed without merging**
