### PR TITLE
[BUG FIX] Fixed basket of seeds and prismapump not placeable due to "Avoid Breaking Enchanted Items" feature

### PR DESCRIPTION
**Pull request by RobotHanzo**

### CODE REVIEW

**Comment by IRONM00N** [comment]
You should add prismapump as well

**Comment by RobotHanzo** [comment]
> You should add prismapump as well

Added

**Comment by ILikePlayingGames** [comment]
Looks good, I’ll merge after learning what these items are and testing. I haven’t played Skyblock in a while.

**Comment by ILikePlayingGames** [comment]
Actually that list is a blacklist and not a whitelist. I'll add a whitelist.

**Comment by ILikePlayingGames** [comment]
Okay I fixed it. It'll be added to the next beta.

**Pull request closed without merging**
