### PR TITLE
Update to 1.12

### PR DESCRIPTION
**Pull request by ErdbeerbaerLP**
I just ported 99% of the mod to 1.12.x
The backpack overlay does not work and the positions of the timers won´t save right now.

### CODE REVIEW

**Comment by biscuut** [comment]
Hi there thanks for the help, but I wanted to port the mod myself, was just trying to finish this update first (was going to do it like right after). In the future I would prefer if you asked me before to make sure it wasn't something I was planning on doing soon. Thanks anyways.

**Comment by Brian-Graham** [comment]
@ErdbeerbaerLP thanks for your hard work! Dev sure is full of himself, berating someone for doing most of the work in an open source project. Know that you're work is appreciated!

**Comment by biscuut** [comment]
@Brian-Graham that's not what I meant, sorry if it sounded that way. The reason I wanted to port it myself after is because I had many unfinished changes, and I thought it would be harder to implement in all those changes than just port it from scratch. If I knew he was going to port it I would have advised doing it after the update to make it easier etc. 

@ErdbeerbaerLP I really appreciate the work you've put in, i'll probably merge this in for the next update, but also implement my new changes which I still haven't committed because they aren't finished lol (and also get a feel of the the 1.12 changes). Also are you in the discord?

**Comment by ErdbeerbaerLP** [comment]
I am not in the discord right now, also the `PlayerInteractEvent` is not cancelable in 1.12 and the backpack overlay is still bugged in my build. everything else seems to work right now. Might join the discord now

**Comment by biscuut** [comment]
Thank you ErdbeerbaerLP for all your work- but yeah Brian-Graham's fork ended up getting merged in (changes are similar to yours), so i'll be closing this one. Thanks again, and feel free to contribute to the new fork if you want (but apparently brian is going to work on remaking a 1.12 version with reflection to keep 1 jar file, so that's going to be interesting)

**Pull request closed without merging**
