### PR TITLE
New setting to disable message with stems/deep caverns ores feature

### PR DESCRIPTION
**Pull request by Keagel**
Added a bit more y-padding so the first setting isn't right against the "Settings" title when in a feature setting.
Don't forget to add the same kind of setting if you pull the nether valuables feature.

### CODE REVIEW

**Comment by biscuut** [comment]
bruh so now we're adding features that disable parts of other features xD

**Comment by Keagel** [comment]
Huh? What do you mean? It's not a feature, it's a setting within each of the two features currently preventing you from mining.

**Comment by biscuut** [comment]
you probably think im blind at this point

**Comment by biscuut** [comment]
thanks for this lol, just an fyi though feature messages are capitalized except for small words, just like you would with a title

**Comment by Keagel** [comment]
No worries lol. Yeah that's mb I didn't pay attention to that.

**Comment by Keagel** [comment]
I think you missed that comment though:
"// Don't forget to add another "else if" when pulling the nether feature"
Sorry lol

**Pull request merged**
