### PR TITLE
Feature: Highlight Enchantments (4/6)

### LINKED ISSUE #390: [Enhancement] Highlight tier 6/4 enchantments
Show tier 6 or 4 enchantments in a different color when hovering over an enchanted item (similar to in sky.lea) to make it easier to find them

FeatureUpvote page: https://skyblockaddons.featureupvote.com/suggestions/94559/highlight-tier-64-enchantments

### PR DESCRIPTION
**Pull request by iHDeveloper**
Highlight any enchantments with the gold color.
If the enchantment level is 4 or 6.

Fixes #390

# Showcases
image
_Photo from @faresbasbs_

### CODE REVIEW

**Comment by iHDeveloper** [comment]
Sorry, forgot to pull from the branch 😅

**Comment by ILikePlayingGames** [comment]
Can you please add a filter for level 4 so it doesn't highlight non-maxed enchants like protection IV?

**Comment by iHDeveloper** [comment]
@ILikePlayingGames
Sure, I added the filter and overwrote the commit :D
The filter list is dynamic (depends on `data.json`). Because Hypixel might add other enchantments.
And, we don't wanna add updates for any new enchantment.

**Comment by biscuut** [comment]
Thank you @iHDeveloper . I've made a bunch of changes on my local branch to organize the "organize enchantments" feature a bit, and add some features like allowing the player to choose the highlight color. I also changed it so instead of highlighting enchantments that are level 4 & 6, we have a list of "special" enchantments and their levels. So this allows for highlighting a lot of different special enchants:

image

**Pull request closed without merging**
