### PR TITLE
[New Feature] Adds the ability to disable spirit sceptre messages + damage display

### PR DESCRIPTION
**Pull request by RobotHanzo**
# Description
This adds the ability for users to disable spirit sceptre messsages, to reduce the spam in the chat
Along with a toggleable display to indicate the hit enemies & damage dealt
# Demostration
[https://cdn.robothanzo.dev/2020-10-17%2018-41-07.mp4](https://cdn.robothanzo.dev/2020-10-17%2018-41-07.mp4) (Without display because this is recorded earlier before I made the display)
 The display
# Try It Out
Download the JAR file from [https://github.com/RobotHanzo/SkyblockAddons/suites/1464955088/artifacts/25127918](https://github.com/RobotHanzo/SkyblockAddons/suites/1464955088/artifacts/25127918)

### CODE REVIEW

**Comment by iHDeveloper** [comment]
What if we turned this into a counter? 🤔

**Comment by RobotHanzo** [comment]
I would be able to do that, I'll submit a PR soon

**Comment by RobotHanzo** [comment]
> What if we turned this into a counter? 🤔

Done 👍

**Comment by RobotHanzo** [comment]
All of the merge conflicts regarding the latest beta update have been resolved

**Comment by ILikePlayingGames** [comment]
Merged in #574. Thank you!

**Pull request closed without merging**
