### PR TITLE
New Feature: Display Potion and Powerup Timers on HUD

### PR DESCRIPTION
**Pull request by Berisan**

### CODE REVIEW

**Comment by Berisan** [comment]
Rebased and squashed the commits into one.

**Comment by biscuut** [comment]
ok great ill be checking this out thanks

**Comment by Berisan** [comment]
Once again rebased to fix merge conflicts.

**Comment by Berisan** [comment]
Actually, somehow with this commit it crashes the game while calculating String width for the Dark Auction Timer?

```
Description: Unexpected error

codes.biscuit.skyblockaddons.utils.nifty.reflection.exceptions.ReflectionException: java.lang.IllegalArgumentException: argument type mismatch
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.accessor.MethodAccessor.invoke(MethodAccessor.java:50)
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.Reflection.invokeMethod(Reflection.java:504)
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.MinecraftReflection$FontRenderer.getStringWidth(MinecraftReflection.java:138)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:668)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderTimersOnly(RenderListener.java:167)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:854)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:561)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:145)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1137)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1127)
	at net.minecraft.client.Minecraft.run(Minecraft.java:384)
	at net.minecraft.client.main.Main.main(Main.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:26)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.accessor.MethodAccessor.invoke(MethodAccessor.java:48)
	... 27 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.accessor.MethodAccessor.invoke(MethodAccessor.java:50)
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.Reflection.invokeMethod(Reflection.java:504)
	at codes.biscuit.skyblockaddons.utils.nifty.reflection.MinecraftReflection$FontRenderer.getStringWidth(MinecraftReflection.java:138)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.drawText(RenderListener.java:668)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.renderTimersOnly(RenderListener.java:167)
	at codes.biscuit.skyblockaddons.listeners.RenderListener.onRenderRegular(RenderListener.java:103)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RenderListener_onRenderRegular_Post.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
	at net.minecraftforge.client.GuiIngameForge.post(GuiIngameForge.java:854)
	at net.minecraftforge.client.GuiIngameForge.renderExperience(GuiIngameForge.java:561)
	at net.minecraftforge.client.GuiIngameForge.renderGameOverlay(GuiIngameForge.java:145)
```

**Comment by biscuut** [comment]
Thank you :)

**Pull request merged**
