### PR TITLE
Fix GSON version conflict

### PR DESCRIPTION
**Pull request by DJtheRedstoner**
Fixes an issue where a newer version of GSON was included by gradle and then used in Utils class.

### CODE REVIEW

**Comment by RobotHanzo** [comment]
Built a version for people having the issue -> [https://github.com/RobotHanzo/SkyblockAddons/actions/runs/433607748](https://github.com/RobotHanzo/SkyblockAddons/actions/runs/433607748)

**Comment by PumpkinXD** [comment]
idk why biscuit don't merge this PR

**Comment by ILikePlayingGames** [comment]
It's been merged in our private branch. I don't think it will be merged into the public development branch since it has basically been abandoned.

**Comment by Phoube** [comment]
Hi @DJtheRedstoner, thanks for the PR. This should be addressed in the development branch as of SBA 1.6.0

**Pull request closed without merging**
