### PR TITLE
Development Features + General Improvements

### PR DESCRIPTION
**Pull request by ILikePlayingGames**
This pull request also includes #247 and #251 because I was working on everything in this branch before moving those to separate branches. 

### Changelog

- Changed the name of the "hide auction house players" feature to "hide players near NPCs" to better reflect its purpose
- Added the ability to hide players around Melody's harp
- Changes to NPC utilities
    - Moved NPC utilities to their own package
    - Added NPC tags for filtering
    - Reorganized the NPC list
- Added a prefix to all chat notifications from the mod
- Developer Mode
    - Developer Mode is a set of features for Skyblock Addons developers
        - Toggle with `/sba dev` (Setting isn't persistent)
        - Features are activated with the developer features hotkey (defaults to none)
    - Current Features
        - Copy Item NBT (by Biscuit): hover over an item and press the key
        - Copy Entity Data: copies some basic data from all players and armor stands in a 3-block radius of the player
    - Fixed copy item NBT triggering too many times
    - Added feature to copy entity data (limited since the client isn't allowed to get NBT from server)
    - Added developer mode strings for localization
    - Moved clipboard handling to DevUtils
- Updated Gradle Wrapper to 4.9 (for compatibility with IntelliJ IDEA 2019.3)
- Included the Github repo URL in the mod metadata
- Bug fixes

### CODE REVIEW

**Comment by ILikePlayingGames** [comment]
Copying item NBT is broken, currently working on fixing

**Comment by ILikePlayingGames** [comment]
Ok it's fixed now. That was pretty hard.

**Comment by biscuut** [comment]
Wow that was a lot to go through lol
Thank you :)

**Comment by ILikePlayingGames** [comment]
You’re welcome! For the don’t open profile with bow feature, I removed it because it was added to skyblock.

**Pull request merged**
