### PR TITLE
Remove magic soup messages

### PR DESCRIPTION
**Pull request by Keagel**

### CODE REVIEW

**Comment by biscuut** [comment]
this would be better in the listener in playerlistener
I don't like using mixins unless its absolutely necessary (more room for error)

**Comment by Keagel** [comment]
Can you actually cancel messages with a listener? I didn't know that.

**Comment by biscuut** [comment]
yep cancelling is usually the best use for a listener, just do `e.setCanceled(true);`

**Comment by Keagel** [comment]
Looks a lot cleaner than mixins huh. Resolved the conflicts at the same time.

**Comment by Keagel** [comment]
Hey maybe I'm blind too. Removed the unnecessary ChatListener and moved the code in the PlayerListener.

**Comment by biscuut** [comment]
honestly why not lol

thanks

**Pull request merged**
