### PR TITLE
Counter for Zealots killed

### PR DESCRIPTION
**Pull request by P0keDev**
Feature requested by a friend. Keeps count of how many Zealots you've killed between finding special Zealots. Only displays in the dragon's nest.

### CODE REVIEW

**Comment by resyal** [comment]
After testing out the Counter a little bit, I'd suggest adding a feature that, once you spawn a special zealot, shows the number of zealots you killed and then fades out. When you spawn a special zealot, you don't really know it was to be happening now, so you donn't look the counter and don't know what number was displayed. My suggestion: When you spawn a special, the number it took you to spawn it shows under the counter for few secs, then fades out.

Thanks !

**Comment by DidiSkywalker** [comment]
Love the feature, and the clever way you're using to detect kills! Some suggestions I have would be a) to persist the counter somehow, not sure if the config would be the right place for that, but maybe in another file. And b) add a dummy text that displays when in GUI editing mode, so the timer can be moved outside the Dragon's Nest.

**Comment by P0keDev** [comment]
> Love the feature, and the clever way you're using to detect kills! Some suggestions I have would be a) to persist the counter somehow, not sure if the config would be the right place for that, but maybe in another file. And b) add a dummy text that displays when in GUI editing mode, so the timer can be moved outside the Dragon's Nest.

good catch, i'll be sure to add dummy text, and look into making the counter persistent

**Comment by biscuut** [comment]
thanks, will edit it a bit

**Pull request merged**
