### PR TITLE
Make Cake Bag Preview show up in AH

### PR DESCRIPTION
**Pull request by ILikePlayingGames**
This feature was suggested on Discord.

### CODE REVIEW

**Comment by biscuut** [comment]
i swear there was a reason i didn't do it.. are you sure you can put filled cake bags into ah?

**Comment by ILikePlayingGames** [comment]
Oh the person who suggested it wasn't trying to sell a cake bag. They said they wanted to see which cakes they had while browsing so they can buy new unique ones.

[Discord Link to Suggestion](https://discordapp.com/channels/450878205294018560/661779804969893900/670374205417848862)

**Comment by ILikePlayingGames** [comment]
I think it might be useful for some to check their backpack while browsing AH too so I’m extending the feature to backpacks too.
I’m working on adding a toggle for it and making it so only cake bags and backpacks in the inventory show previews.

**Comment by ILikePlayingGames** [comment]
I found an issue. The settings under Backpack Preview are rendering in the incorrect order for some reason even though their order in the code is correct. I'm not familiar with how the GUI works so I'm not sure why that is happening.

**Comment by biscuut** [comment]
ah i get what you mean-

and it looks good, thank you. I will check out the issue with the settings order.

**Pull request merged**
