### PR TITLE
[BUG FIX] Fixed axes with reforges not compatible with the cooldown features

### PR DESCRIPTION
**Pull request by RobotHanzo**
# Description
This fixes Issue #438 by using .contains instead of .equals when matching axes, and replace the way it searches maps
# Try It Out
[https://github.com/RobotHanzo/SkyblockAddons/suites/1393459570/artifacts/23067682](https://github.com/RobotHanzo/SkyblockAddons/suites/1393459570/artifacts/23067682)

### CODE REVIEW

**Comment by FacioZMafii** [comment]
tested and works perfectly

**Comment by ILikePlayingGames** [comment]
This looks good, I’ll test it later.

**Comment by ILikePlayingGames** [comment]
Just confirmed that it works. Thank you @RobotHanzo!

**Comment by MangoMonkey2004** [comment]
The link doesn't work. It seems the webpage isn't there anymore. Can you repost a new link or something for me pls? @RobotHanzo

**Pull request merged**
