### PR TITLE
[Bugfix] Make Health & Mana Bar Visible again

### PR DESCRIPTION
**Pull request by Randomfly1**
### **Description:**
this fixes issue #431 by removing two getAlpha() functions in RenderListener.java

### CODE REVIEW

**Comment by RobotHanzo** [comment]
Built the jar for you, link avaliable at [https://github.com/RobotHanzo/SkyblockAddons/suites/1399556759/artifacts/23240757](https://github.com/RobotHanzo/SkyblockAddons/suites/1399556759/artifacts/23240757)

**Comment by Randomfly1** [comment]
This is off topic, but how did you create that download link?
Sorry if its obvious, but I'm new to GitHub...

**Comment by RobotHanzo** [comment]
> This is off topic, but how did you create that download link?
> Sorry if its obvious, but I'm new to GitHub...

Using GitHub Actions, you can Google for the usage

**Comment by RobotHanzo** [comment]
Please do not try it on the branch you are using to PR

**Comment by Llama0319** [comment]
@RobotHanzo Tysm I had this same problem and it fixed it!

**Comment by Llama0319** [comment]
Could you possibly fix the issue with sba where the game crashes when I try to make anything chroma?

**Comment by Randomfly1** [comment]
As far as I can tell the game crashing after enabling chroma is a problem with the development branch itself and not with this PR in particular. I can however independently try to fix the issue although I won't make any promises.

**Comment by Llama0319** [comment]
@Randomfly1 that would be great if you could try and fix it but if not that's ok.

**Comment by Phoube** [comment]
Hi @Randomfly1, thanks for the PR, and sorry it took so long for this issue to be closed. Although I think the getAlpha remains in the current development branch, the underlying issue should be addressed as of SBA version 1.6.0.

**Pull request closed without merging**
