### PR TITLE
[Feature] Outbid sound alert

### PR DESCRIPTION
**Pull request by skycatminepokie**
FeatureUpvote page: https://skyblockaddons.featureupvote.com/suggestions/92657/outbid-sound-alert

### CODE REVIEW

**Comment by skycatminepokie** [comment]
Anyone know if I should bother with keeping this conflict-free? Every time there's a new feature, I have to edit my feature number and merge upstream into my fork :/

**Comment by iHDeveloper** [comment]
> Anyone know if I should bother with keeping this conflict-free? Every time there's a new feature, I have to edit my feature number and merge upstream into my fork :/

You don't have to keep up with the added feature conflict

**Comment by skycatminepokie** [comment]
Alright, sounds good. Thanks!

**Comment by skycatminepokie** [comment]
Is there any ETA when PRs are going to start being reviewed again?

**Comment by ILikePlayingGames** [comment]
Merged in #574. Thank you!

**Pull request closed without merging**
