### PR TITLE
Full 1.12/1.12.2 Support

### PR DESCRIPTION
**Pull request by Brian-Graham**
The only things that need fixing are the following:
- Enchanted items do not appear as enchanted in backpacks
- Potions appears as null items in backpacks

### CODE REVIEW

**Comment by biscuut** [comment]
oh wow now we have two 1.12 forks dont know which one to merge lol

**Comment by Brian-Graham** [comment]
I've fixed everything except for non-potion potions in backpack preview. Not sure what the other PR hasn't fixed.

**Comment by biscuut** [comment]
will be closing this one for now as you have permission to push directly

**Comment by mer2329** [comment]
is this going to be compiled or do i continue to use ErdbeerbaerLP's fork?

**Pull request closed without merging**
