### PR TITLE
change dflt keybind of copynbt to LMENU for macos

### PR DESCRIPTION
**Pull request by RayDeeUx**
now macos players can copy nbt right away!

### CODE REVIEW

**Comment by RayDeeUx** [comment]
(also i gradlew built and tested already, everything looks good)

**Comment by My-Name-Is-Jeff** [comment]
zzzzzz

**Review by ILikePlayingGames — COMMENTED** [review]
I'll make it set RCONTROL for Windows/Linux and LMENU for Mac

**Comment by ILikePlayingGames** [comment]
Can you please test if this works? I added an OS check so it's changed to LMENU just on MacOS.

**Comment by RayDeeUx** [comment]
Getting a consistent roof above my head has been a bit tricky this week, so I'm sorry for the late reply.

Got brian damage from SkyClient to test the workflow artifact on his ancient MacBook and behavior was as expected (LMENU as default) on an older version of macOS/OS X. I'd safely assume the same applies to macOS Monterey and all major macOS versions in between.

Got SansTheLurker to test the same workflow artifact on a Linux distro that I never had the chance to get the name of as well as Windows (I'm assuming either 10 or 11) and the default was RCONTROL for both OSes.

Will try to find more macOS folks to confirm my hypothesis during the coming days, but so far so good.

**Comment by RayDeeUx** [comment]
Also, just a minor correction on the comment you added just before the ternary operator to determine OS: Apple *does* manufacture/sell their own keyboards with an RCONTROL key, however such keyboards are often excluded from the box when someone initially purchases a Mac machine.

**Comment by ILikePlayingGames** [comment]
Sorry to hear that. I hope you're doing better now. Don't worry about time, there's no rush to merge this. Thank you for finding people to test it!

**Comment by RayDeeUx** [comment]
forgot to mention but phoube (also macOS) has also tested the workflow artifact from this PR without any unexpected results

**Comment by ILikePlayingGames** [comment]
Thanks! Going to merge

**Pull request merged**
